// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrsK46HeFi6cDzgGdzqKp45LL_qicuaWQ',
    appId: '1:943770465204:android:e66c64e66dfb589d97f8e1',
    messagingSenderId: '943770465204',
    projectId: 'hierosecret-87b5c',
    storageBucket: 'hierosecret-87b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd1Y2eLIarOYCtwCoOorMQjFYLUiJija0',
    appId: '1:943770465204:ios:8fc1c4de3d33017c97f8e1',
    messagingSenderId: '943770465204',
    projectId: 'hierosecret-87b5c',
    storageBucket: 'hierosecret-87b5c.firebasestorage.app',
    iosBundleId: 'com.hierosecret.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ad9WHDTCP7zu3FBjRFwVBQDSxvxrn48',
    appId: '1:943770465204:web:76e4242f3989472197f8e1',
    messagingSenderId: '943770465204',
    projectId: 'hierosecret-87b5c',
    authDomain: 'hierosecret-87b5c.firebaseapp.com',
    storageBucket: 'hierosecret-87b5c.firebasestorage.app',
    measurementId: 'G-NBQS7RYC9H',
  );
}
