class Country {
  final String name;
  final String flag;

  Country(this.name, this.flag);
}

List<Country> countries = [
  Country('American Samoa', 'assets/flags/as.png'),
  Country('United Arab Emirates', 'assets/flags/ae.png'),
  Country('Afghanistan', 'assets/flags/af.png'),
  Country('Antigua and Barbuda', 'assets/flags/ag.png'),
  Country('Anguilla', 'assets/flags/ai.png'),
  Country('Albania', 'assets/flags/al.png'),
  Country('Armenia', 'assets/flags/am.png'),
  Country('Angola', 'assets/flags/ao.png'),
  Country('Antarctica', 'assets/flags/aq.png'),
  Country('Argentina', 'assets/flags/ar.png'),
  Country('American Samoa', 'assets/flags/as.png'),
  Country('Austria', 'assets/flags/at.png'),
  Country('Australia', 'assets/flags/au.png'),
  Country('Aruba', 'assets/flags/aw.png'),
  Country('Åland Islands', 'assets/flags/ax.png'),
  Country('Azerbaijan', 'assets/flags/az.png'),
  Country('Bosnia and Herzegovina', 'assets/flags/ba.png'),
  Country('Barbados', 'assets/flags/bb.png'),
  Country('Bangladesh', 'assets/flags/bd.png'),
  Country('Belgium', 'assets/flags/be.png'),
  Country('Burkina Faso', 'assets/flags/bf.png'),
  Country('Bulgaria', 'assets/flags/bg.png'),
  Country('Bahrain', 'assets/flags/bh.png'),
  Country('Burundi', 'assets/flags/bi.png'),
  Country('Benin', 'assets/flags/bj.png'),
  Country('Saint Barthélemy', 'assets/flags/bl.png'),
  Country('Bermuda', 'assets/flags/bm.png'),
  Country('Brunei Darussalam', 'assets/flags/bn.png'),
  Country('Bolivia (Plurinational State of)', 'assets/flags/bo.png'),
  Country('Bonaire, Sint Eustatius and Saba', 'assets/flags/bq.png'),
  Country('Brazil', 'assets/flags/br.png'),
  Country('Bahamas', 'assets/flags/bs.png'),
  Country('Bhutan', 'assets/flags/bt.png'),
  Country('Bouvet Island', 'assets/flags/bv.png'),
  Country('Botswana', 'assets/flags/bw.png'),
  Country('Belarus', 'assets/flags/by.png'),
  Country('Belize', 'assets/flags/bz.png'),
  Country('Canada', 'assets/flags/ca.png'),
  Country('Cocos (Keeling) Islands', 'assets/flags/cc.png'),
  Country('Democratic Republic of the Congo', 'assets/flags/cd.png'),
  Country('Central African Republic', 'assets/flags/cf.png'),
  Country('Republic of the Congo', 'assets/flags/cg.png'),
  Country('Switzerland', 'assets/flags/ch.png'),
  Country('Côte d\'Ivoire', 'assets/flags/ci.png'),
  Country('Cook Islands', 'assets/flags/ck.png'),
  Country('Chile', 'assets/flags/cl.png'),
  Country('Cameroon', 'assets/flags/cm.png'),
  Country('China', 'assets/flags/cn.png'),
  Country('Colombia', 'assets/flags/co.png'),
  Country('Costa Rica', 'assets/flags/cr.png'),
  Country('Cuba', 'assets/flags/cu.png'),
  Country('Cabo Verde', 'assets/flags/cv.png'),
  Country('Curaçao', 'assets/flags/cw.png'),
  Country('Christmas Island', 'assets/flags/cx.png'),
  Country('Cyprus', 'assets/flags/cy.png'),
  Country('Czechia', 'assets/flags/cz.png'),
  Country('Germany', 'assets/flags/de.png'),
  Country('Djibouti', 'assets/flags/dj.png'),
  Country('Denmark', 'assets/flags/dk.png'),
  Country('Dominica', 'assets/flags/dm.png'),
  Country('Dominican Republic', 'assets/flags/do.png'),
  Country('Algeria', 'assets/flags/dz.png'),
  Country('Ecuador', 'assets/flags/ec.png'),
  Country('Estonia', 'assets/flags/ee.png'),
  Country('Egypt', 'assets/flags/eg.png'),
  Country('Western Sahara', 'assets/flags/eh.png'),
  Country('Eritrea', 'assets/flags/er.png'),
  Country('Spain', 'assets/flags/es.png'),
  Country('Ethiopia', 'assets/flags/et.png'),
  Country('European Union', 'assets/flags/eu.png'),
  Country('Finland', 'assets/flags/fi.png'),
  Country('Fiji', 'assets/flags/fj.png'),
  Country('Falkland Islands (Malvinas)', 'assets/flags/fk.png'),
  Country('Micronesia (Federated States of)', 'assets/flags/fm.png'),
  Country('Faroe Islands', 'assets/flags/fo.png'),
  Country('France', 'assets/flags/fr.png'),
  Country('Gabon', 'assets/flags/ga.png'),
  Country('England', 'assets/flags/gb-eng.png'),
  Country('Northern Ireland', 'assets/flags/gb-nir.png'),
  Country('Scotland', 'assets/flags/gb-sct.png'),
  Country('Wales', 'assets/flags/gb-wls.png'),
  Country('United Kingdom', 'assets/flags/gb.png'),
  Country('Grenada', 'assets/flags/gd.png'),
  Country('Georgia', 'assets/flags/ge.png'),
  Country('French Guiana', 'assets/flags/gf.png'),
  Country('Guernsey', 'assets/flags/gg.png'),
  Country('Ghana', 'assets/flags/gh.png'),
  Country('Gibraltar', 'assets/flags/gi.png'),
  Country('Greenland', 'assets/flags/gl.png'),
  Country('Gambia', 'assets/flags/gm.png'),
  Country('Guinea', 'assets/flags/gn.png'),
  Country('Guadeloupe', 'assets/flags/gp.png'),
  Country('Equatorial Guinea', 'assets/flags/gq.png'),
  Country('Greece', 'assets/flags/gr.png'),
  Country(
      'South Georgia and the South Sandwich Islands', 'assets/flags/gs.png'),
  Country('Guatemala', 'assets/flags/gt.png'),
  Country('Guam', 'assets/flags/gu.png'),
  Country('Guinea-Bissau', 'assets/flags/gw.png'),
  Country('Guyana', 'assets/flags/gy.png'),
  Country('Hong Kong', 'assets/flags/hk.png'),
  Country('Heard Island and McDonald Islands', 'assets/flags/hm.png'),
  Country('Honduras', 'assets/flags/hn.png'),
  Country('Croatia', 'assets/flags/hr.png'),
  Country('Haiti', 'assets/flags/ht.png'),
  Country('Hungary', 'assets/flags/hu.png'),
  Country('Indonesia', 'assets/flags/id.png'),
  Country('Ireland', 'assets/flags/ie.png'),
  Country('Israel', 'assets/flags/il.png'),
  Country('Isle of Man', 'assets/flags/im.png'),
  Country('India', 'assets/flags/in.png'),
  Country('British Indian Ocean Territory', 'assets/flags/io.png'),
  Country('Iraq', 'assets/flags/iq.png'),
  Country('Iran (Islamic Republic of)', 'assets/flags/ir.png'),
  Country('Iceland', 'assets/flags/is.png'),
  Country('Italy', 'assets/flags/it.png'),
  Country('Jersey', 'assets/flags/je.png'),
  Country('Jamaica', 'assets/flags/jm.png'),
  Country('Jordan', 'assets/flags/jo.png'),
  Country('Japan', 'assets/flags/jp.png'),
  Country('Kenya', 'assets/flags/ke.png'),
  Country('Kyrgyzstan', 'assets/flags/kg.png'),
  Country('Cambodia', 'assets/flags/kh.png'),
  Country('Kiribati', 'assets/flags/ki.png'),
  Country('Comoros', 'assets/flags/km.png'),
  Country('Saint Kitts and Nevis', 'assets/flags/kn.png'),
  Country('North Korea', 'assets/flags/kp.png'),
  Country('South Korea', 'assets/flags/kr.png'),
  Country('Kuwait', 'assets/flags/kw.png'),
  Country('Cayman Islands', 'assets/flags/ky.png'),
  Country('Kazakhstan', 'assets/flags/kz.png'),
  Country('Lao People\'s Democratic Republic', 'assets/flags/la.png'),
  Country('Lebanon', 'assets/flags/lb.png'),
  Country('Saint Lucia', 'assets/flags/lc.png'),
  Country('Liechtenstein', 'assets/flags/li.png'),
  Country('Sri Lanka', 'assets/flags/lk.png'),
  Country('Liberia', 'assets/flags/lr.png'),
  Country('Lesotho', 'assets/flags/ls.png'),
  Country('Lithuania', 'assets/flags/lt.png'),
  Country('Luxembourg', 'assets/flags/lu.png'),
  Country('Latvia', 'assets/flags/lv.png'),
  Country('Libya', 'assets/flags/ly.png'),
  Country('Morocco', 'assets/flags/ma.png'),
  Country('Monaco', 'assets/flags/mc.png'),
  Country('Moldova (Republic of)', 'assets/flags/md.png'),
  Country('Montenegro', 'assets/flags/me.png'),
  Country('Saint Martin (French part)', 'assets/flags/mf.png'),
  Country('Madagascar', 'assets/flags/mg.png'),
  Country('Marshall Islands', 'assets/flags/mh.png'),
  Country('North Macedonia', 'assets/flags/mk.png'),
  Country('Mali', 'assets/flags/ml.png'),
  Country('Myanmar', 'assets/flags/mm.png'),
  Country('Mongolia', 'assets/flags/mn.png'),
  Country('Macao', 'assets/flags/mo.png'),
  Country('Northern Mariana Islands', 'assets/flags/mp.png'),
  Country('Martinique', 'assets/flags/mq.png'),
  Country('Mauritania', 'assets/flags/mr.png'),
  Country('Montserrat', 'assets/flags/ms.png'),
  Country('Malta', 'assets/flags/mt.png'),
  Country('Mauritius', 'assets/flags/mu.png'),
  Country('Maldives', 'assets/flags/mv.png'),
  Country('Malawi', 'assets/flags/mw.png'),
  Country('Mexico', 'assets/flags/mx.png'),
  Country('Malaysia', 'assets/flags/my.png'),
  Country('Mozambique', 'assets/flags/mz.png'),
  Country('Namibia', 'assets/flags/na.png'),
  Country('New Caledonia', 'assets/flags/nc.png'),
  Country('Niger', 'assets/flags/ne.png'),
  Country('Norfolk Island', 'assets/flags/nf.png'),
  Country('Nigeria', 'assets/flags/ng.png'),
  Country('Nicaragua', 'assets/flags/ni.png'),
  Country('Netherlands', 'assets/flags/nl.png'),
  Country('Norway', 'assets/flags/no.png'),
  Country('Nepal', 'assets/flags/np.png'),
  Country('Nauru', 'assets/flags/nr.png'),
  Country('Niue', 'assets/flags/nu.png'),
  Country('New Zealand', 'assets/flags/nz.png'),
  Country('Oman', 'assets/flags/om.png'),
  Country('Panama', 'assets/flags/pa.png'),
  Country('Peru', 'assets/flags/pe.png'),
  Country('French Polynesia', 'assets/flags/pf.png'),
  Country('Papua New Guinea', 'assets/flags/pg.png'),
  Country('Philippines', 'assets/flags/ph.png'),
  Country('Pakistan', 'assets/flags/pk.png'),
  Country('Poland', 'assets/flags/pl.png'),
  Country('Saint Pierre and Miquelon', 'assets/flags/pm.png'),
  Country('Pitcairn', 'assets/flags/pn.png'),
  Country('Puerto Rico', 'assets/flags/pr.png'),
  Country('Palestine, State of', 'assets/flags/ps.png'),
  Country('Portugal', 'assets/flags/pt.png'),
  Country('Palau', 'assets/flags/pw.png'),
  Country('Paraguay', 'assets/flags/py.png'),
  Country('Qatar', 'assets/flags/qa.png'),
  Country('Réunion', 'assets/flags/re.png'),
  Country('Romania', 'assets/flags/ro.png'),
  Country('Serbia', 'assets/flags/rs.png'),
  Country('Russia', 'assets/flags/ru.png'),
  Country('Rwanda', 'assets/flags/rw.png'),
  Country('Saudi Arabia', 'assets/flags/sa.png'),
  Country('Solomon Islands', 'assets/flags/sb.png'),
  Country('Seychelles', 'assets/flags/sc.png'),
  Country('Sudan', 'assets/flags/sd.png'),
  Country('Sweden', 'assets/flags/se.png'),
  Country('Singapore', 'assets/flags/sg.png'),
  Country(
      'Saint Helena, Ascension and Tristan da Cunha', 'assets/flags/sh.png'),
  Country('Slovenia', 'assets/flags/si.png'),
  Country('Svalbard and Jan Mayen', 'assets/flags/sj.png'),
  Country('Slovakia', 'assets/flags/sk.png'),
  Country('Sierra Leone', 'assets/flags/sl.png'),
  Country('San Marino', 'assets/flags/sm.png'),
  Country('Senegal', 'assets/flags/sn.png'),
  Country('Somalia', 'assets/flags/so.png'),
  Country('Suriname', 'assets/flags/sr.png'),
  Country('South Sudan', 'assets/flags/ss.png'),
  Country('São Tomé and Príncipe', 'assets/flags/st.png'),
  Country('El Salvador', 'assets/flags/sv.png'),
  Country('Sint Maarten (Dutch part)', 'assets/flags/sx.png'),
  Country('Syrian Arab Republic', 'assets/flags/sy.png'),
  Country('Eswatini', 'assets/flags/sz.png'),
  Country('Turks and Caicos Islands', 'assets/flags/tc.png'),
  Country('Chad', 'assets/flags/td.png'),
  Country('French Southern Territories', 'assets/flags/tf.png'),
  Country('Togo', 'assets/flags/tg.png'),
  Country('Thailand', 'assets/flags/th.png'),
  Country('Tajikistan', 'assets/flags/tj.png'),
  Country('Tokelau', 'assets/flags/tk.png'),
  Country('Timor-Leste', 'assets/flags/tl.png'),
  Country('Turkmenistan', 'assets/flags/tm.png'),
  Country('Tunisia', 'assets/flags/tn.png'),
  Country('Tonga', 'assets/flags/to.png'),
  Country('Turkey', 'assets/flags/tr.png'),
  Country('Trinidad and Tobago', 'assets/flags/tt.png'),
  Country('Tuvalu', 'assets/flags/tv.png'),
  Country('Taiwan, Province of China', 'assets/flags/tw.png'),
  Country('Tanzania, United Republic of', 'assets/flags/tz.png'),
  Country('Ukraine', 'assets/flags/ua.png'),
  Country('Uganda', 'assets/flags/ug.png'),
  Country('United States Minor Outlying Islands', 'assets/flags/um.png'),
  Country('United States of America', 'assets/flags/us.png'),
  Country('Uruguay', 'assets/flags/uy.png'),
  Country('Uzbekistan', 'assets/flags/uz.png'),
  Country('Holy See', 'assets/flags/va.png'),
  Country('Saint Vincent and the Grenadines', 'assets/flags/vc.png'),
  Country('Venezuela (Bolivarian Republic of)', 'assets/flags/ve.png'),
  Country('British Virgin Islands', 'assets/flags/vg.png'),
  Country('United States Virgin Islands', 'assets/flags/vi.png'),
  Country('Viet Nam', 'assets/flags/vn.png'),
  Country('Vanuatu', 'assets/flags/vu.png'),
  Country('Wallis and Futuna', 'assets/flags/wf.png'),
  Country('Samoa', 'assets/flags/ws.png'),
  Country('Kosovo', 'assets/flags/xk.png'),
  Country('Yemen', 'assets/flags/ye.png'),
  Country('Mayotte', 'assets/flags/yt.png'),
  Country('South Africa', 'assets/flags/za.png'),
  Country('Zambia', 'assets/flags/zm.png'),
  Country('Zimbabwe', 'assets/flags/zw.png')
];
